thermal_image_topic_name: image_raw
colored_thermal_image_topic_name: image_colored
camera_frame_id: thermal_camera
camera_name: thermal_camera
camera_info_url: file://${ROS_HOME}/camera_info/${NAME}.yaml
interpolate_dead_pixels: true
calibrate_dead_pixels: false
mean_compensation: false
calibrate_mean_compensation: false
denoise: true
show_debug_images: false
offset: -6.0
output_center_temperature: false
